name: Java CI with Gradle
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build -x test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/springrestapi-0.0.1-SNAPSHOT.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: build/libs/
      - name: Display artifact
        run: |
          pwd
          ls -alt
      - name: Install SSH Client
        run: sudo apt install -y openssh-client
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to OCI
        run: >
          
          scp -o StrictHostKeyChecking=no build/libs/*.jar $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH


          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
              pkill -f 'java -jar' || true 		        
              nohup java -jar $REMOTE_PATH/*.jar > app.log 2>&1 &
            EOF
